version: "3.9"

services:
  pi-face:
    image: face-pi-face:latest
    container_name: pi-face
    restart: unless-stopped

    environment:
      DATA_ROOT: /data
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "5000"

    ports:
      - "5000:5000"

    volumes:
      - $HOME/project/face/data:/data
      - $HOME/project/face/inspireface-cache:/root/.inspireface
